version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  groups:
    compatible-updates:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
- package-ecosystem: bundler
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  groups:
    compatible-updates:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
- package-ecosystem: pip
  directory: /tools
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  groups:
    compatible-updates:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
